// Generated by CoffeeScript 1.9.2
(function() {
  var pongular;

  pongular = require('pongular').pongular;

  require('pong-q');

  pongular.module('pong-mark', ['pong-q']).service('postmark', function() {
    return require('Postmark');
  }).service('configuredPostmark', function(postmark, postmarkConfig) {
    return postmark(postmarkConfig.apiKey);
  }).service('$mailer', function($promise, configuredPostmark) {
    return function(attrs) {
      return $promise(function(d) {
        return configuredPostmark.send(attrs, function(error, success) {
          if (error) {
            return d.reject(error.message);
          } else {
            return d.resolve();
          }
        });
      });
    };
  });

}).call(this);
